captum_ig:
  _target_: CaptumExplainer
  algorithm: IntegratedGradients
  call:
    target: 0
  visualisers:
    - _target_: CaptumImageVisualiser
captum_saliency:
  _target_: CaptumExplainer
  algorithm: Saliency
  call:
    target: 0
  visualisers:
    - _target_: CaptumImageVisualiser