# @package _global_

reporting:
  _target_: PDFReporter
  filename: report.pdf
  multirun_report: true

hydra:
  callbacks:
    reporting_sweep:
      _target_: raitap.reporting.hydra_callback.ReportingSweepCallback
