"""Public Python API.

Thin facade exposing the orchestrator entry point and the schema dataclasses.
Per-module builders (``raitap.transparency.captum``, ``raitap.robustness.torchattacks``,
``raitap.metrics.classification``, …) are generated by
:class:`raitap._adapters.AdapterMixin` and resolved via each module's
``__getattr__``. No central registry to edit when adding a new adapter.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

from hydra_zen import instantiate

from raitap.configs import set_output_root
from raitap.configs.schema import (
    AppConfig,
    DataConfig,
    LabelsConfig,
    MetricsConfig,
    ModelConfig,
    ReportingConfig,
    RobustnessConfig,
    TrackingConfig,
    TransparencyConfig,
)
from raitap.pipeline.orchestrator import run as _orchestrator_run

if TYPE_CHECKING:
    from raitap.pipeline.outputs import RunOutputs

__all__ = [
    "AppConfig",
    "DataConfig",
    "LabelsConfig",
    "MetricsConfig",
    "ModelConfig",
    "ReportingConfig",
    "RobustnessConfig",
    "TrackingConfig",
    "TransparencyConfig",
    "instantiate",
    "run",
]


def run(
    config: AppConfig,
    *,
    verbose: bool = True,
    output_root: str | Path | None = None,
) -> RunOutputs:
    """Run the full pipeline programmatically.

    No chdir, no logging hijack. Pass ``verbose=False`` to suppress the
    summary panel + report-generation log line.

    Outputs (metrics, reports, transparency artefacts) are written under
    ``output_root``. When ``None``, mirrors Hydra's default and writes to
    ``./outputs/<YYYY-MM-DD>/<HH-MM-SS>/`` so the caller's cwd stays clean.
    """
    try:
        existing_root = config._output_root  # type: ignore[attr-defined]
    except Exception:
        existing_root = None
    if output_root is None and existing_root is None:
        now = datetime.now()
        output_root = Path("outputs") / now.strftime("%Y-%m-%d") / now.strftime("%H-%M-%S")
    if output_root is not None:
        set_output_root(config, output_root)
    return _orchestrator_run(config, verbose=verbose)
