"""Public Python API.

Thin facade exposing the orchestrator entry point and the schema dataclasses.
Per-module builders (``raitap.transparency.captum``, ``raitap.robustness.torchattacks``,
``raitap.metrics.classification``, …) are generated by
:class:`raitap._adapters.AdapterMixin` and resolved via each module's
``__getattr__``. No central registry to edit when adding a new adapter.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

from hydra_zen import instantiate

from raitap.configs import set_output_root
from raitap.configs.schema import (
    AppConfig,
    DataConfig,
    LabelsConfig,
    MetricsConfig,
    ModelConfig,
    ReportingConfig,
    RobustnessConfig,
    TrackingConfig,
    TransparencyConfig,
)
from raitap.pipeline.orchestrator import run as _orchestrator_run

if TYPE_CHECKING:
    from raitap.pipeline.outputs import RunOutputs

__all__ = [
    "AppConfig",
    "DataConfig",
    "LabelsConfig",
    "MetricsConfig",
    "ModelConfig",
    "ReportingConfig",
    "RobustnessConfig",
    "TrackingConfig",
    "TransparencyConfig",
    "instantiate",
    "run",
]


def run(
    config: AppConfig,
    *,
    verbose: bool = True,
    output_root: str | Path | None = None,
    auto_install_deps: bool = False,
    exec_global: bool = False,
    acknowledge_preprocessing_off: bool = False,
    acknowledge_preprocessing_exec: bool = False,
    allow_unsafe_pickle: bool = False,
) -> RunOutputs:
    """Run the full pipeline programmatically.

    No chdir, no logging hijack. Pass ``verbose=False`` to suppress the
    summary panel + report-generation log line.

    Outputs (metrics, reports, transparency artefacts) are written under
    ``output_root``. When ``None``, mirrors Hydra's default and writes to
    ``./outputs/<YYYY-MM-DD>/<HH-MM-SS>/`` so the caller's cwd stays clean.

    Pass ``auto_install_deps=True`` to opt into the same auto-deps flow the
    ``raitap`` CLI uses behind ``--allow-project-edit`` / ``-y``: the call
    walks ``config`` for adapter ``_target_`` references, infers the
    matching extras, runs ``uv add raitap[<extras>]`` (or ``pip install``
    when uv is absent), and re-execs the current Python process so the
    freshly-installed packages are visible. ``exec_global=True`` consents
    to ``pip install`` against the base interpreter when no venv is
    active (the pip-side analogue of ``--exec-global``). Idempotent: a
    sentinel env var short-circuits the second pass after the re-exec.

    Without either flag, ``run`` assumes the extras the config needs are
    already installed (the typical case after the CLI bootstrap or a
    manual ``uv sync``); a missing adapter library surfaces as the usual
    ``ModuleNotFoundError`` from the adapter import chain.

    ``acknowledge_preprocessing_off=True`` silences the "preprocessing is
    OFF" warning when ``data.preprocessing`` is unset and the caller has
    already normalised inputs upstream (CLI analogue:
    ``--acknowledge-preprocessing-off``).
    ``acknowledge_preprocessing_exec=True`` is the explicit consent for
    ``data.preprocessing: <path>.py``, which executes arbitrary Python code
    from disk (CLI analogue: ``--allow-preprocessing-exec`` / ``-yp``).
    ``allow_unsafe_pickle=True`` consents to loading pickled ``nn.Module``
    checkpoints (executes arbitrary code embedded in the file; CLI
    analogue: ``--allow-unsafe-pickle``).
    """
    if auto_install_deps:
        # Lazy import so callers who do not opt in don't pay for the
        # bootstrap module's imports.
        from raitap.deps.bootstrap import install_raitap_deps

        install_raitap_deps(config, allow_project_edit=True, exec_global=exec_global)

    try:
        existing_root = config._output_root  # type: ignore[attr-defined]
    except Exception:
        existing_root = None
    if output_root is None and existing_root is None:
        now = datetime.now()
        output_root = Path("outputs") / now.strftime("%Y-%m-%d") / now.strftime("%H-%M-%S")
    if output_root is not None:
        set_output_root(config, output_root)
    return _orchestrator_run(
        config,
        verbose=verbose,
        acknowledge_preprocessing_off=acknowledge_preprocessing_off,
        acknowledge_preprocessing_exec=acknowledge_preprocessing_exec,
        allow_unsafe_pickle=allow_unsafe_pickle,
    )
