"""Sphinx hook: generate one adapter-reference page from raitap's registry.

Walks ``raitap._adapters._BUILDERS`` (populated by every ``@adapters.<family>``
decorator) and writes ``docs/modules/_generated_adapters.md``: one anchored
table per registry group (``use`` key | algorithms | extra | supported tasks).
Module doc pages pull individual group tables in with a MyST ``{include}``
fence plus ``:start-after:``/``:end-before:`` markers (see ``_anchor`` below).

Runs on ``builder-inited`` -- before any source file is read -- so the
generated page exists on disk by the time Sphinx parses the ``{include}``
directives that reference it.

Real adapter classes live behind heavy optional deps (torch, captum, shap,
foolbox, torchattacks, ...) that the docs build environment does not install
(see ``autodoc_mock_imports`` in ``conf.py``). This reuses that same mock list
via :func:`sphinx.ext.autodoc.mock.mock` so ``import raitap`` plus the
registry walk succeed without those deps -- exactly like autodoc's own
imports for ``automodule``/``autoclass``.

Writing one single generated page (not per-symbol ``automodule``/``autoclass``
directives scattered across pages) sidesteps the duplicate-object build
failure that hits a shared symbol re-exported from two packages under
``:imported-members:``.
"""

from __future__ import annotations

import importlib
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from sphinx.application import Sphinx

GENERATED_PAGE = "modules/_generated_adapters.md"

# Canonical group display order; groups not listed here (future families,
# third-party plugin groups) are appended alphabetically after.
_GROUP_ORDER = (
    "transparency",
    "robustness",
    "metrics",
    "reporting",
    "tracking",
    "data/inputs",
    "data/labels",
    "_unscoped",
)

TABLE_HEADERS = ("`use` key", "Algorithms", "Extra", "Supported tasks")


def _anchor(group: str, edge: str) -> str:
    return f"<!-- raitap-adapters:{group}:{edge} -->"


def _escape_cell(value: str) -> str:
    return value.replace("|", r"\|")


def _format_names(names: list[str]) -> str:
    if not names:
        return "—"
    return ", ".join(f"`{name}`" for name in sorted(names))


def _adapter_row(*, registry_name: str, cls: type, extras: dict[str, str]) -> str:
    algorithm_registry = getattr(cls, "algorithm_registry", None)
    algorithms = _format_names(list(algorithm_registry)) if algorithm_registry else "—"

    supported_tasks = getattr(cls, "supported_tasks", None)
    tasks = _format_names([str(task) for task in supported_tasks]) if supported_tasks else "—"

    extra = extras.get(cls.__name__, "")
    extra_cell = f"`{extra}`" if extra else "—"

    cells = [f"`{registry_name}`", algorithms, extra_cell, tasks]
    return "| " + " | ".join(_escape_cell(cell) for cell in cells) + " |"


def _group_table_lines(
    *,
    registry_names: list[str],
    target_fqn: dict[str, str],
    extras: dict[str, str],
) -> list[str]:
    header_line = "| " + " | ".join(TABLE_HEADERS) + " |"
    separator_line = "| " + " | ".join("---" for _ in TABLE_HEADERS) + " |"
    lines = [header_line, separator_line]
    for registry_name in sorted(registry_names):
        fqn = target_fqn.get(registry_name)
        if fqn is None:
            lines.append(f"| `{registry_name}` | — | — | — |")
            continue
        module_name, _, cls_name = fqn.rpartition(".")
        try:
            module = importlib.import_module(module_name)
            cls = getattr(module, cls_name)
        except Exception:
            # A third-party plugin adapter's own deps may genuinely be missing
            # even under the mock list; degrade to an "unavailable" row
            # instead of failing the whole doc build.
            lines.append(f"| `{registry_name}` | — | — | — |")
            continue
        lines.append(_adapter_row(registry_name=registry_name, cls=cls, extras=extras))
    return lines


def _build_generated_page(mock_imports: list[str]) -> str:
    from sphinx.ext.autodoc.mock import mock  # pyright: ignore[reportPrivateImportUsage]

    with mock(mock_imports):
        importlib.import_module("raitap")  # side-effect import; discard the module object
        from raitap._adapters import _BUILDERS, _TARGET_FQN, ADAPTER_EXTRAS
        from raitap.configs import register_configs

        register_configs()  # idempotent; imports every in-tree family + plugins

        groups = list(_BUILDERS)
        ordered_groups = [g for g in _GROUP_ORDER if g in groups]
        ordered_groups += sorted(g for g in groups if g not in _GROUP_ORDER)

        sections: list[str] = [
            "<!-- Generated by docs/_ext/raitap_adapters.py from raitap._adapters "
            "registries. Do not edit by hand. -->",
            "",
        ]
        for group in ordered_groups:
            sections.append(_anchor(group, "start"))
            sections.extend(
                _group_table_lines(
                    registry_names=list(_BUILDERS[group]),
                    target_fqn=_TARGET_FQN.get(group, {}),
                    extras=ADAPTER_EXTRAS,
                )
            )
            sections.append(_anchor(group, "end"))
            sections.append("")
        return "\n".join(sections).rstrip() + "\n"


def generate_adapter_reference(app: Sphinx) -> None:
    content = _build_generated_page(list(app.config.autodoc_mock_imports))
    target = Path(app.srcdir) / GENERATED_PAGE
    target.parent.mkdir(parents=True, exist_ok=True)
    if not target.exists() or target.read_text() != content:
        target.write_text(content)


def setup(app: Sphinx) -> dict[str, bool]:
    app.connect("builder-inited", generate_adapter_reference)
    return {
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }
