_target_: raitap.metrics.detection_tm.DetectionMetrics
box_format: xyxy
iou_type: bbox
iou_thresholds: null
rec_thresholds: null
max_detection_thresholds: null
class_metrics: false
extended_summary: false
average: macro
backend: pycocotools
