from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol


@dataclass
class AssessmentContext:
    assessment_name: str
    model_source: str
    data_name: str


class Tracker(Protocol):
    def start_assessment(self, context: AssessmentContext) -> None: ...
    def log_config(self, config: Any) -> None: ...
    def log_model(self, model: Any, artifact_path: str = "model") -> None: ...
    def log_dataset(self, dataset_info: dict[str, Any], artifact_path: str = "dataset") -> None: ...
    def log_transparency(self, results: dict[str, Any]) -> None: ...
    def log_metrics(self, metrics: dict[str, Any]) -> None: ...
    def finalize(self, status="FINISHED") -> None: ...
