defaults:
  - _self_
  - transparency: demo
  - model: vit_b32
  - data: isic2018
  - metrics: classification
  - reporting: disabled

hardware: gpu
experiment_name: demo

hydra:
  callbacks:
    reporting_sweep:
      _target_: raitap.reporting.hydra_callback.ReportingSweepCallback
